profile = "prod"

[server]
addr = "0.0.0.0"
port = 8_000

[db]
host = "postgres-service"
port = 5_432
username = "username"
password = "password"
database_name = "database_name"
max_connections = 5

[redis]
username = "redis-user"
password = "303fiwe9i2ll3dsi21k1-2k-F"
host = "redis-service"
port = 6_379
database_name = "madeirareport"

[email]
username = "email_user"
password = "email_pass"
host = "smtp.gmail.com"
port = 1_025

[sentry]
key = "https://cf57e25524b4966607be2121590a7665@o376701.ingest.sentry.io/4506826357604352"

[secret]
private_access_key = "static/key/private_access_rsa_key.pem"
public_access_key = "static/key/public_access_rsa_key.pem"
private_refresh_key = "static/key/private_refresh_rsa_key.pem"
public_refresh_key = "static/key/public_refresh_rsa_key.pem"

[worker]
failed_task_delay = 100

[http]
timeout = 10

