apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: application
          image: ghcr.io/13dev/madeirareport-api:latest
          imagePullPolicy: Always
          env:
            - name: APP_DB__HOST
              value: "postgres-db"
          volumeMounts:
            - name: app-data
              mountPath: /logs
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data