apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-db
  template:
    metadata:
      labels:
        app: redis-db
    spec:
      containers:
        - name: redis-db
          image: redis:latest
          env:
            - name: REDIS_USER
              value: "redis-user"
            - name: REDIS_PASSWORD
              value: "303fiwe9i2ll3dsi21k1-2k-F"
            - name: REDIS_DB
              value: ""