name: Build, Test and Deploy to Prod

on:
  push:
    branches:
      - master

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Copy docker/prod to droplet
        run: scp -o StrictHostKeyChecking=no docker/prod ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:~

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            chmod +x run.sh
            ./run.sh