name: build docker image

on:
  workflow_call:

permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ghcr.io/${{ github.repository_owner }}/madeirareport-api:latest
#
#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Copy docker/prod to droplet
        uses: appleboy/scp-action@master
        with:
          source: 'docker/prod/*'
          target: '~'
          host: ${{ vars.DROPLET_HOST }}
          port: 22
          username: ${{ vars.DROPLET_USER }}
          key: |
            echo "${{ secrets.DROPLET_PRIVATE_KEY }}" | base64 -d


      - name: Transfer files via SCP
        shell: bash
        run: |
          echo $DROPLET_KEY | base64 -d > ssh_private_key.pem
          chmod 600 ssh_private_key.pem
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H -t rsa $HOST > ~/.ssh/known_hosts
          scp -i ssh_private_key.pem -r docker/prod/docker-compose.yml $USER@$HOST:~
        env:
          DROPLET_KEY: ${{ secrets.DROPLET_PRIVATE_KEY }}
          HOST: ${{ vars.DROPLET_HOST }}
          USER: ${{ vars.DROPLET_USER }}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            chmod +x run.sh
            ./run.sh
