name: build docker image

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: info

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ghcr.io/${{ github.repository_owner }}/madeirareport-api:latest
#
#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Transfer files via SCP
        run: |
          echo "${{ secrets.DROPLET_PRIVATE_KEY }}" > ssh_private_key.pem
          chmod 600 ssh_private_key.pem
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          scp -i ssh_private_key.pem -r docker/prod root@164.92.220.100:~
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            chmod +x run.sh
            ./run.sh
